paths:
  input: "/app/host/data/input_images"   # Caminho DENTRO do container
  output: "/app/host/data/output_results" # Caminho DENTRO do container
  onnx_model: "model/model_wood_vessel_segmenter.onnx"
parameters:
  resolution_um_px: 1.0638
  min_area_px: 100
  threshold: 0.5
  ignore_border: false
  save_masks: true